[package]
name = "ariadne_next"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
insta = "1.34.0"
itertools = "0.12.0"
yansi = "0.5.1"
